"""Submission acceptance tests; Supabase is replaced at the database boundary."""
from datetime import datetime, timezone
from types import SimpleNamespace
from unittest.mock import MagicMock, patch

import pytest
from flask import Flask

from app.routes.event_requests import event_requests_bp
from app.schemas import event_request as schema
from test_event_request_schema import valid_payload


@pytest.fixture
def client():
    app = Flask(__name__)
    app.register_blueprint(event_requests_bp)
    app.testing = True
    return app.test_client()


@pytest.fixture
def table():
    with patch('app.services.db.get_supabase') as database:
        table = MagicMock()
        database.return_value.table.return_value = table
        def insert(record):
            table.execute.return_value = SimpleNamespace(data=[{
                **record, 'event_request_id': 42,
            }])
            return table
        table.insert.side_effect = insert
        yield table


def test_completed_request_is_submitted_with_id_timestamp_and_confirmation(client, table):
    before = datetime.now(timezone.utc)
    response = client.post('/api/event-requests', json=valid_payload())
    after = datetime.now(timezone.utc)
    assert response.status_code == 201
    assert response.json['message'] == 'Event request submitted successfully.'
    row = response.json['event_request']
    assert row['event_request_id'] == 42
    assert row['status'] == 'submitted'
    assert before <= datetime.fromisoformat(row['submitted_at']) <= after
    # IDs are generated by the database, never supplied by the client.
    assert 'event_request_id' not in table.insert.call_args.args[0]
    assert row['event_name'] == 'Orientation Night'


@pytest.mark.parametrize('field', schema.MANDATORY_FOR_SUBMISSION)
def test_missing_information_has_field_error_and_never_writes(client, table, field):
    payload = valid_payload()
    del payload[field]
    response = client.post('/api/event-requests', json=payload)
    assert response.status_code == 400
    assert 'required' in response.json['errors'][field]
    assert 'message' not in response.json
    table.insert.assert_not_called()


@pytest.mark.parametrize('changes,field', [
    ({'capacity_needed': 0}, 'capacity_needed'),
    ({'capacity_needed': 1.5}, 'capacity_needed'),
    ({'start_datetime': 'invalid'}, 'start_datetime'),
    ({'end_datetime': '2000-01-01T00:00:00Z'}, 'end_datetime'),
    ({'room_layout': 'invalid'}, 'room_layout'),
    ({'required_facilities': ['invalid']}, 'required_facilities'),
    ({'equipment_requirements': [{'equipment_type': 'mic', 'quantity': 0}]}, 'equipment_requirements'),
    ({'event_name': '   '}, 'event_name'),
    ({'status': 'approved'}, '_body'),
    ({'event_request_id': 123}, '_body'),
    ({'submitted_at': '2000-01-01T00:00:00Z'}, '_body'),
])
def test_invalid_information_never_writes(client, table, changes, field):
    response = client.post('/api/event-requests', json=valid_payload(**changes))
    assert response.status_code == 400
    assert field in response.json['errors']
    table.insert.assert_not_called()


@pytest.mark.parametrize('body', [[], 'text', 123, None, {'save_as_draft': 'false'}])
def test_malformed_body_returns_readable_error(client, table, body):
    response = client.post('/api/event-requests', json=body)
    assert response.status_code == 400
    assert response.json['error']
    table.insert.assert_not_called()


def test_database_failure_returns_error_without_confirmation(client, table):
    table.insert.side_effect = RuntimeError('database offline')
    response = client.post('/api/event-requests', json=valid_payload())
    assert response.status_code == 502
    assert 'Please try again' in response.json['error']
    assert 'message' not in response.json
    assert 'event_request' not in response.json


def test_empty_database_response_is_not_reported_as_success(client, table):
    table.insert.side_effect = None
    table.insert.return_value.execute.return_value = SimpleNamespace(data=[])
    response = client.post('/api/event-requests', json=valid_payload())
    assert response.status_code == 502
    assert response.json['error']


def test_draft_is_not_marked_submitted(client, table):
    response = client.post('/api/event-requests', json={'event_name': 'Draft', 'save_as_draft': True})
    assert response.status_code == 201
    assert response.json['event_request']['status'] == 'draft'
    assert 'submitted_at' not in table.insert.call_args.args[0]


def test_saved_details_can_be_read_for_review(client):
    row = {**valid_payload(), 'event_request_id': 42, 'status': 'draft'}
    with patch('app.routes.event_requests.get_event_request', return_value=row):
        response = client.get('/api/event-requests/42')
    assert response.status_code == 200
    assert response.json == row


def test_incomplete_draft_cannot_be_submitted(client):
    with patch('app.services.event_request_service.require_event_request', return_value={
        'event_request_id': 42, 'status': 'draft',
    }), patch('app.services.event_request_service.mark_submitted') as write:
        response = client.post('/api/event-requests/42/submit')
    assert response.status_code == 400
    assert 'event_name' in response.json['errors']
    write.assert_not_called()
